output_dict = {
    "summaries": {
        'Abstract': 'This paper proposes a self-modeling based diagnosis system aimed at addressing challenges such as scalability and resiliency within Software-Defined Networks (SDN) and Network Functions Virtualization (NFV). The authors introduce templates for modeling network components, facilitating runtime generation of diagnosis models.',
        'I. INTRODUCTION': 'The introduction discusses the significance of SDN and NFV in improving network management and reducing operational costs, highlighting challenges like resiliency that necessitate self-diagnosis mechanisms to enhance network recovery processes.',
        'II. MOTIVATION': 'This section presents the challenges of modeling dependencies in dynamic SDN and NFV environments, focusing on the need for a self-modeling algorithm capable of adapting to runtime changes in both VNFs and network topologies.',
        'III. RELATED WORK ON MODEL-BASED DIAGNOSIS': 'The related work section reviews existing model-based diagnosis approaches, identifying limitations in granularity and dynamic modeling, and sets the stage for the proposed enhancements in the current work.',
        'IV. SELF-MODELING BASED DIAGNOSIS FRAMEWORK': 'This section outlines the framework for the self-modeling diagnosis process, including template definitions and methods for constructing a global dependency graph from network topology.',
        'V. VALIDATION OF DIAGNOSIS MODULE': 'The validation confirms the effectiveness of the proposed self-modeling diagnosis system through various tests in a simulated SDN environment, demonstrating model generation and diagnosis performance under different conditions.',
        'VI. CONCLUSIONS AND FUTURE WORK': 'The conclusion reviews the main achievements of the proposed diagnosis framework and outlines future research directions focused on reducing uncertainty in diagnosis and enhancing learning capabilities within the model.'
    },
    "related_work": {
        "Self-Modeling Based Diagnosis of Software-Defined Networks": "The related work highlights existing approaches to model-based diagnosis primarily focused on static topologies, discussing their shortcomings in handling dynamically changing environments, especially in the context of SDN and NFV. The paper advances the state of the art by proposing a self-modeling diagnosis that dynamically constructs dependency graphs while considering finer granularities of network components."
    },
    "logical_chain": "The article presents a comprehensive argumentation process that starts by identifying key challenges in diagnosing software-defined and virtualized network environments, leading to the proposal of a self-modeling framework that systematically constructs detailed dependency graphs necessary for effective diagnosis. The method enhances diagnosis granularity and automation while addressing the limitations of existing models, establishing a well-supported case for improving network resiliency through self-diagnosing capabilities."
}

output_dict_cited_by = {'cited_by_0': {'title': 'Automatic belief network modeling via policy inference for SDN fault localization', 'link': 'https://link.springer.com/article/10.1186/s13174-016-0043-y', 'snippet': 'Fault localization for SDN becomes one of the most critical but difficult tasks. Existing tools typically only address a specific part of the problem (eg, control plane verification, flow …', 'authors': [{'name': 'Y Tang', 'link': 'https://scholar.google.com/citations?user=aT4H2uMAAAAJ&hl=en&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=aT4H2uMAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'aT4H2uMAAAAJ'}], 'resources': [{'title': 'springer.com', 'file_format': 'PDF', 'link': 'https://link.springer.com/content/pdf/10.1186/s13174-016-0043-y.pdf'}]}, 'cited_by_1': {'title': 'A survey of fault management in network virtualization environments: Challenges and solutions', 'link': 'https://ieeexplore.ieee.org/abstract/document/8877749/', 'snippet': 'The advent of 5G and the ever increasing stringent requirements in terms of bandwidth, latency, and quality of service pushes the boundaries of what is feasible with legacy Mobile …', 'authors': [{'name': 'S Cherrared', 'link': 'https://scholar.google.com/citations?user=xE-e3ZMAAAAJ&hl=en&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=xE-e3ZMAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'xE-e3ZMAAAAJ'}, {'name': 'S Imadali', 'link': 'https://scholar.google.com/citations?user=4at5xPQAAAAJ&hl=en&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=4at5xPQAAAAJ&engine=google_scholar_author&hl=en', 'author_id': '4at5xPQAAAAJ'}], 'resources': [{'title': 'hal.science', 'file_format': 'PDF', 'link': 'https://inria.hal.science/hal-02370378/file/survey_TNSM.pdf'}]}, 'cited_by_2': {'title': 'Self-healing topology discovery protocol for software-defined networks', 'link': 'https://ieeexplore.ieee.org/abstract/document/8319433/', 'snippet': 'This letter presents the design of a self-healing protocol for automatic discovery and maintenance of the network topology in software-defined networks. The proposed protocol …', 'authors': [{'name': 'L Ochoa-Aday', 'link': 'https://scholar.google.com/citations?user=crMxdqEAAAAJ&hl=en&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=crMxdqEAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'crMxdqEAAAAJ'}, {'name': 'C Cervello-Pastor', 'link': 'https://scholar.google.com/citations?user=kKmxAToAAAAJ&hl=en&oi=sra', 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=kKmxAToAAAAJ&engine=google_scholar_author&hl=en', 'author_id': 'kKmxAToAAAAJ'}], 'resources': [{'title': 'upc.edu', 'file_format': 'PDF', 'link': 'https://upcommons.upc.edu/bitstream/handle/2117/115551/self_topo_discov_SDN.pdf?sequence=1'}]}}